name: Build and Use Other Private Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current project
      - name: Checkout current project
        uses: actions/checkout@v2

      # Checkout the other private project
      - name: Checkout other private project
        run: |
          git clone https://gallex:${{secrets.PRIVATE_REPO_TOKEN}}@github.com/printspirit/designer.git 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 或者你想要使用的版本
      
      - name: Install dependencies
        run: |
          cd designer
          npm install

      - name: Build the project
        run: |
          cd designer 
          npm run build
