name: Build and Use Other Private Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current project
      - name: Checkout current project
        uses: actions/checkout@v2

      # Checkout the other private project
      - name: Checkout other private project
        run: |
          git clone https://gallex:${{secrets.PRIVATE_REPO_TOKEN}}@github.com/printspirit/spirit.git 

      - name: Set up Go 
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      
      # Install dependencies and build the other project
      - name: Build other project
        run: |
          cd spirit
          go build -tags center
